start "node 1" /min cmd /k "pbft-default.exe N0"
start "node 2" /min cmd /k "pbft-default.exe N1"
start "node 3" /min cmd /k "pbft-default.exe N2"
start "node 4" /min cmd /k "pbft-default.exe N3"
start "node 5" /min cmd /k "pbft-default.exe N4"
start "node 6" /min cmd /k "pbft-default.exe N5"
start "node 7" /min cmd /k "pbft-default.exe N6"
start "node 8" /min cmd /k "pbft-default.exe N7"
start "node 9" /min cmd /k "pbft-default.exe N8"
start "node 10" /min cmd /k "pbft-default.exe N9"
start "node 11" /min cmd /k "pbft-default.exe N10"
start "node 12" /min cmd /k "pbft-default.exe N11"

